apiVersion: v1
kind: Service
metadata:
  name: platter-service
  labels:
    app: platter
spec:
  type: ClusterIP
  selector:
    app: platter
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
